image:
  repository: ghcr.io/snothub/mcp-for-argocd
  tag: "latest"
  pullPolicy: IfNotPresent

auth:
  enabled: false
  tokens:
  - 8803f621acc3898df1d7a8f514bc3602551a0681a8f747bd4e43c3c5849d57a7 # danijel

argocd:
  existingSecret: argocd-mcp-credentials

ingress:
  enabled: true
  host: argocdmcp.forteapps.net
