apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-mcp.fullname" . }}
  labels:
    {{- include "argocd-mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ if .Values.auth.enabled }}8080{{ else }}http{{ end }}
      protocol: TCP
      name: http
  selector:
    {{- include "argocd-mcp.selectorLabels" . | nindent 4 }}
